import { Product, Category, TranslationKey, Coupon, WebsiteSettings } from '../types';

export interface Governorate {
  id: string;
  nameAr: string;
  nameEn: string;
  shippingFee: number;
}

export const EGYPT_GOVERNORATES: Governorate[] = [
  { id: 'cairo', nameAr: 'القاهرة', nameEn: 'Cairo', shippingFee: 50 },
  { id: 'giza', nameAr: 'الجيزة', nameEn: 'Giza', shippingFee: 50 },
  { id: 'alexandria', nameAr: 'الإسكندرية', nameEn: 'Alexandria', shippingFee: 65 },
  { id: 'qalyubia', nameAr: 'القليوبية', nameEn: 'Qalyubia', shippingFee: 60 },
  { id: 'sharqia', nameAr: 'الشرقية', nameEn: 'Sharqia', shippingFee: 70 },
  { id: 'dakahlia', nameAr: 'الدقهلية', nameEn: 'Dakahlia', shippingFee: 70 },
  { id: 'gharbia', nameAr: 'الغربية', nameEn: 'Gharbia', shippingFee: 70 },
  { id: 'monufia', nameAr: 'المنوفية', nameEn: 'Monufia', shippingFee: 70 },
  { id: 'beheira', nameAr: 'البحيرة', nameEn: 'Beheira', shippingFee: 75 },
  { id: 'suez', nameAr: 'السويس', nameEn: 'Suez', shippingFee: 80 },
  { id: 'ismailia', nameAr: 'الإسماعيلية', nameEn: 'Ismailia', shippingFee: 80 },
  { id: 'port_said', nameAr: 'بور سعيد', nameEn: 'Port Said', shippingFee: 80 },
  { id: 'fayoum', nameAr: 'الفيوم', nameEn: 'Fayoum', shippingFee: 85 },
  { id: 'beni_suef', nameAr: 'بني سويف', nameEn: 'Beni Suef', shippingFee: 85 },
  { id: 'minya', nameAr: 'المنيا', nameEn: 'Minya', shippingFee: 90 },
  { id: 'asyut', nameAr: 'أسيوط', nameEn: 'Asyut', shippingFee: 95 },
  { id: 'sohag', nameAr: 'سوهاج', nameEn: 'Sohag', shippingFee: 100 },
  { id: 'qena', nameAr: 'قنا', nameEn: 'Qena', shippingFee: 110 },
  { id: 'luxor', nameAr: 'الأقصر', nameEn: 'Luxor', shippingFee: 120 },
  { id: 'aswan', nameAr: 'أسوان', nameEn: 'Aswan', shippingFee: 130 },
  { id: 'red_sea', nameAr: 'البحر الأحمر', nameEn: 'Red Sea', shippingFee: 110 },
  { id: 'matrouh', nameAr: 'مطروح', nameEn: 'Matrouh', shippingFee: 120 },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'sneakers',
    nameAr: 'أحذية رياضية',
    nameEn: 'Premium Sneakers',
    slug: 'sneakers',
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'formal',
    nameAr: 'أحذية كلاسيكية ورسمية',
    nameEn: 'Classic & Formal',
    slug: 'formal',
    image: 'https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'boots',
    nameAr: 'أحذية برقبة / هاف بوت',
    nameEn: 'Premium Boots',
    slug: 'boots',
    image: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'sandals',
    nameAr: 'صنادل وشباشب مريحة',
    nameEn: 'Sandals & Slippers',
    slug: 'sandals',
    image: 'https://images.unsplash.com/photo-1603487226258-414a77450c7c?auto=format&fit=crop&q=80&w=600',
  },
];

export const INITIAL_PRODUCTS: Product[] = [];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'c1',
    code: 'WELCOME10',
    discountType: 'percentage',
    value: 10,
    minOrderValue: 1000,
    active: true,
    expiresAt: '2027-12-31T23:59:59Z',
  },
  {
    id: 'c2',
    code: 'EGYPT150',
    discountType: 'fixed',
    value: 150,
    minOrderValue: 2000,
    active: true,
    expiresAt: '2027-12-31T23:59:59Z',
  },
];

export const DEFAULT_SETTINGS: WebsiteSettings = {
  siteNameAr: 'أتوم للأحذية الفاخرة | AtoM Shoes',
  siteNameEn: 'AtoM Premium Footwear Store',
  contactPhone: '+20 100 123 4567',
  contactEmail: 'support@atom-egypt.com',
  whatsappNumber: '+9647813745417', // support whatsapp from request
  facebookUrl: 'https://facebook.com/atom.egypt',
  instagramUrl: 'https://instagram.com/atom.egypt',
  shippingFeeEgypt: 50,
  freeShippingThreshold: 3000,
  vodafoneCashNumber: '01032120351',
  paymobApiKey: '',
  paymobSecretKey: '',
  paymobIntegrationId: '',
  paymobIframeId: '',
  futureProviderApiKey: '',
  supabaseUrl: '',
  supabaseAnonKey: '',
  supabaseServiceRoleKey: '',
  cloudinaryCloudName: '',
  cloudinaryApiKey: '',
  cloudinaryApiSecret: '',
  resendApiKey: '',
};

export const FAQ_ITEMS = [
  {
    qAr: 'ما هي مدة التوصيل داخل مصر؟',
    qEn: 'What is the delivery time within Egypt?',
    aAr: 'يستغرق التوصيل عادة من 2 إلى 4 أيام عمل لمحافظات القاهرة الكبرى، ومن 3 إلى 6 أيام عمل لباقي المحافظات.',
    aEn: 'Delivery typically takes 2–4 business days for Greater Cairo, and 3–6 business days for other governorates.',
  },
  {
    qAr: 'هل يتوفر الدفع عند الاستلام؟',
    qEn: 'Is Cash on Delivery (COD) available?',
    aAr: 'نعم، الدفع عند الاستلام هو الخيار الافتراضي والآمن لكافة المنتجات في جميع أنحاء مصر.',
    aEn: 'Yes, Cash on Delivery is available and represents the default secure option for all locations in Egypt.',
  },
  {
    qAr: 'ما هي سياسة الاسترجاع والاستبدال الخاصة بكم؟',
    qEn: 'What is your return and exchange policy?',
    aAr: 'نقدم سياسة استرجاع مريحة خلال 14 يوماً من تاريخ الاستلام للمنتجات غير المستخدمة في تغليفها الأصلي.',
    aEn: 'We offer a convenient 14-day return and exchange window from the date of delivery, provided the item is unused and in its original packaging.',
  },
  {
    qAr: 'كيف يمكنني تتبع طلبي؟',
    qEn: 'How can I track my order?',
    aAr: 'بمجرد تأكيد طلبك، سنرسل لك إشعاراً بالرمز الخاص بطلبك، ويمكنك التواصل مع الدعم الفني عبر الواتساب لتتبع حالته في أي وقت.',
    aEn: 'Once your order is confirmed, you will receive a confirmation code. You can contact our support team via WhatsApp to track your order status live.',
  },
];

export const TRANSLATIONS: Record<'ar' | 'en', Record<TranslationKey, string>> = {
  ar: {
    appName: 'أتوم | AtoM',
    searchPlaceholder: 'ابحث عن أحذية رياضية، كلاسيكية، رسمية أو هاف بوت...',
    categories: 'الأقسام',
    featuredCategories: 'مجموعاتنا الراقية',
    bestSellers: 'الأكثر مبيعاً',
    newArrivals: 'وصل حديثاً',
    offers: 'العروض والمميزات',
    addToCart: 'إضافة إلى الحقيبة',
    addedToCart: 'تمت الإضافة ✔',
    buyNow: 'شراء الآن',
    wishlist: 'المفضلة',
    cart: 'حقيبة التسوق',
    checkout: 'إتمام الطلب',
    myProfile: 'حسابي الشخصي',
    myOrders: 'طلباتي',
    adminPanel: 'لوحة التحكم',
    logout: 'تسجيل الخروج',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب جديد',
    currency: 'جنيه مصري',
    home: 'الرئيسية',
    about: 'من نحن',
    contact: 'اتصل بنا',
    faq: 'الأسئلة الشائعة',
    privacyPolicy: 'سياسة الخصوصية',
    terms: 'الشروط والأحكام',
    whatsappSupport: 'الدعم المباشر عبر واتساب',
    newsletterTitle: 'انضم إلى نادي أتوم الحصري',
    newsletterDesc: 'اشترك لتصلك أحدث تصاميم الأحذية الفاخرة، العروض الحصرية، ومقاساتك المفضلة قبل الجميع.',
    subscribe: 'اشتراك',
    allProducts: 'جميع المقتنيات',
    filterBy: 'تصفية حسب',
    sortBy: 'ترتيب حسب',
    priceLowHigh: 'السعر: من الأقل إلى الأعلى',
    priceHighLow: 'السعر: من الأعلى إلى الأقل',
    ratingHighLow: 'التقييم: الأعلى تقييماً',
    stockStatus: 'حالة المخزون',
    inStock: 'متوفر في المخزن',
    outOfStock: 'نفد من المخزن',
    emptyCart: 'حقيبة التسوق الخاصة بك فارغة حالياً.',
    emptyWishlist: 'قائمة الأمنيات الخاصة بك فارغة.',
    subtotal: 'المجموع الفرعي',
    shipping: 'الشحن والتوصيل',
    freeShipping: 'شحن مجاني',
    total: 'الإجمالي النهائي',
    checkoutTitle: 'تفاصيل الشحن والتسليم',
    fullName: 'الاسم بالكامل',
    phoneNumber: 'رقم الهاتف المحمول',
    governorate: 'المحافظة',
    city: 'المدينة / المنطقة',
    street: 'اسم الشارع / الميدان',
    building: 'رقم المبنى / العقار',
    apartment: 'رقم الشقة / الطابق',
    orderNotes: 'ملاحظات إضافية على الطلب (اختياري)',
    placeOrder: 'تأكيد طلب الشراء والدفع عند الاستلام',
    orderSuccess: 'تهانينا! تم تسجيل طلبك بنجاح',
    orderSuccessDesc: 'نشكرك على تسوقك من أتوم. سنقوم بمراجعة الطلب والتواصل معك هاتفياً لتأكيد الشحن خلال 24 ساعة.',
    orderId: 'رقم الطلب',
    orderStatus: 'حالة الطلب الحالي',
    pending: 'قيد المراجعة',
    waiting_payment: 'بانتظار التحقق من الدفع',
    confirmed: 'تم تأكيد الطلب',
    processing: 'قيد التجهيز',
    shipped: 'تم الشحن للعميل',
    delivered: 'تم التوصيل والتحصيل',
    cancelled: 'تم إلغاء الطلب',
    cashOnDelivery: 'الدفع عند الاستلام (كاش)',
    continueShopping: 'العودة لتصفح المعرض',
    noOrders: 'لا توجد طلبات سابقة مسجلة حتى الآن.',
    adminDashboard: 'نظرة عامة على المتجر',
    adminProducts: 'المقتنيات والمنتجات',
    adminOrders: 'طلبات العملاء',
    adminCustomers: 'سجل العملاء',
    adminCoupons: 'قسائم التخفيض',
    adminSettings: 'إعدادات المتجر',
    totalSales: 'إجمالي المبيعات',
    totalOrders: 'عدد الطلبات',
    activeCustomers: 'العملاء المسجلين',
    activeCoupons: 'القسائم النشطة',
    recentOrders: 'آخر الطلبات الواردة',
    productManagement: 'إدارة المنتجات والمخزون',
    addNewProduct: 'إضافة منتج جديد',
    editProduct: 'تعديل بيانات المنتج',
    deleteProduct: 'حذف المنتج نهائياً',
    save: 'حفظ التغييرات',
    cancel: 'إلغاء',
    productNameAr: 'الاسم بالعربية',
    productNameEn: 'الاسم بالإنجليزية',
    descriptionAr: 'الوصف بالعربية',
    descriptionEn: 'الوصف بالإنجليزية',
    priceLabel: 'سعر البيع (جنيه)',
    comparePriceLabel: 'السعر الأصلي للمقارنة (اختياري)',
    stockLabel: 'الكمية المتوفرة في المخزن',
    categoryLabel: 'القسم الرئيسي',
    imageUrls: 'روابط الصور (مفصولة بأسطر جديدة)',
    viewStore: 'الذهاب إلى المتجر',
    searchProducts: 'بحث في المنتجات...',
    filters: 'الفلاتر',
    reviews: 'آراء وتقييمات العملاء',
    writeReview: 'أضف تقييمك للمنتج',
    rating: 'التقييم',
    comment: 'التعليق / المراجعة',
    submitReview: 'نشر التقييم',
    allCategories: 'كل الفئات',
    couponCode: 'كود الخصم',
    apply: 'تطبيق',
    couponApplied: 'تم تطبيق الكود بنجاح!',
    invalidCoupon: 'كود خصم غير صحيح أو لا يستوفي الشروط',
    savedAddresses: 'العناوين المحفوظة للشحن',
    addAddress: 'إضافة عنوان شحن جديد',
    noAddresses: 'لم تقم بإضافة أي عنوان بعد.',
    addressDeleted: 'تم حذف العنوان بنجاح.',
    notifications: 'الإشعارات والتنبيهات',
    markAllRead: 'تحديد الكل كمقروء',
    error404Title: 'عذراً، الصفحة غير موجودة',
    error404Desc: 'الرابط الذي تحاول الوصول إليه غير متوفر أو ربما تم نقله.',
    backToHome: 'العودة إلى الصفحة الرئيسية',
    unauthorized: 'غير مسموح بالدخول',
    unauthorizedDesc: 'تحتاج إلى صلاحيات مدير النظام للوصول إلى هذه اللوحة.',
    searchResultFor: 'نتائج البحث عن',
  },
  en: {
    appName: 'AtoM Premium',
    searchPlaceholder: 'Search sneakers, classic leather shoes, boots...',
    categories: 'Categories',
    featuredCategories: 'Our Fine Collections',
    bestSellers: 'Best Sellers',
    newArrivals: 'New Arrivals',
    offers: 'Premium Values',
    addToCart: 'Add to Bag',
    addedToCart: 'Added ✔',
    buyNow: 'Buy Now',
    wishlist: 'Wishlist',
    cart: 'Shopping Bag',
    checkout: 'Checkout',
    myProfile: 'My Profile',
    myOrders: 'My Orders',
    adminPanel: 'Admin Dashboard',
    logout: 'Log Out',
    login: 'Log In',
    register: 'Sign Up',
    currency: 'EGP',
    home: 'Home',
    about: 'About Us',
    contact: 'Contact Us',
    faq: 'FAQ',
    privacyPolicy: 'Privacy Policy',
    terms: 'Terms of Service',
    whatsappSupport: 'WhatsApp Support',
    newsletterTitle: 'Join the Exclusive Circle',
    newsletterDesc: 'Subscribe for elite footwear designs, invite-only sales, and size restock alerts.',
    subscribe: 'Subscribe',
    allProducts: 'All Offerings',
    filterBy: 'Filter By',
    sortBy: 'Sort By',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    ratingHighLow: 'Rating: Highest First',
    stockStatus: 'Stock Status',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    emptyCart: 'Your shopping bag is currently empty.',
    emptyWishlist: 'Your wishlist is currently empty.',
    subtotal: 'Subtotal',
    shipping: 'Shipping & Delivery',
    freeShipping: 'Free Shipping',
    total: 'Grand Total',
    checkoutTitle: 'Delivery Information',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    governorate: 'Governorate',
    city: 'City / Area',
    street: 'Street Address',
    building: 'Building Name/No.',
    apartment: 'Apartment/Floor No.',
    orderNotes: 'Additional Delivery Notes (Optional)',
    placeOrder: 'Confirm Order & Cash on Delivery',
    orderSuccess: 'Thank you! Your order was received',
    orderSuccessDesc: 'We appreciate your order at AtoM. We will verify and process your delivery via call within 24 hours.',
    orderId: 'Order ID',
    orderStatus: 'Order Status',
    pending: 'Pending Review',
    waiting_payment: 'Waiting for Payment Verification',
    confirmed: 'Confirmed',
    processing: 'Processing',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    cashOnDelivery: 'Cash on Delivery (COD)',
    continueShopping: 'Continue Shopping',
    noOrders: 'You have no order history yet.',
    adminDashboard: 'Store Overview',
    adminProducts: 'Product Offerings',
    adminOrders: 'Customer Orders',
    adminCustomers: 'Customer Directory',
    adminCoupons: 'Coupon Codes',
    adminSettings: 'Store Customization',
    totalSales: 'Total Sales',
    totalOrders: 'Total Orders',
    activeCustomers: 'Customers',
    activeCoupons: 'Coupons Active',
    recentOrders: 'Recent Incoming Orders',
    productManagement: 'Product & Inventory Management',
    addNewProduct: 'Add New Product',
    editProduct: 'Edit Product Details',
    deleteProduct: 'Delete Product',
    save: 'Save Changes',
    cancel: 'Cancel',
    productNameAr: 'Arabic Name',
    productNameEn: 'English Name',
    descriptionAr: 'Arabic Description',
    descriptionEn: 'English Description',
    priceLabel: 'Selling Price (EGP)',
    comparePriceLabel: 'Original Compare Price (Optional)',
    stockLabel: 'In-Stock Quantity',
    categoryLabel: 'Primary Category',
    imageUrls: 'Image URLs (one per line)',
    viewStore: 'View Store',
    searchProducts: 'Search products...',
    filters: 'Filters',
    reviews: 'Customer Reviews',
    writeReview: 'Write a Review',
    rating: 'Rating',
    comment: 'Comment / Review Text',
    submitReview: 'Publish Review',
    allCategories: 'All Categories',
    couponCode: 'Promo Code',
    apply: 'Apply',
    couponApplied: 'Promo code applied successfully!',
    invalidCoupon: 'Invalid promo code or requirements not met',
    savedAddresses: 'Saved Delivery Addresses',
    addAddress: 'Add New Address',
    noAddresses: 'You have not added any addresses yet.',
    addressDeleted: 'Address removed successfully.',
    notifications: 'Notifications',
    markAllRead: 'Mark all as read',
    error404Title: 'Page Not Found',
    error404Desc: 'The link you are trying to reach is not available or has been moved.',
    backToHome: 'Back to Home',
    unauthorized: 'Access Denied',
    unauthorizedDesc: 'You require administrator permissions to view this panel.',
    searchResultFor: 'Search results for',
  },
};
